Rails.application.routes.draw do
  get 'naps/index'
  get 'naps/new'
  get 'naps/create'
  get 'naps/show'
  get 'naps/edit'
  get 'naps/update'
  get 'naps/destroy'
  get 'users/index'
  get 'users/new'
  get 'users/create'
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  get 'users/destroy'
  get 'cats/index'
  get 'cats/new'
  get 'cats/create'
  get 'cats/show'
  get 'cats/edit'
  get 'cats/update'
  get 'cats/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
